INSERT INTO pais (nombre) VALUES  ('Colombia');
INSERT INTO pais (nombre) VALUES  ('Venezuela');
INSERT INTO pais (nombre) VALUES  ('Argentina');
INSERT INTO pais (nombre) VALUES  ('Perú');
INSERT INTO pais (nombre) VALUES  ('Ecuador');
INSERT INTO pais (nombre) VALUES  ('UK');
INSERT INTO pais (nombre) VALUES  ('US');
INSERT INTO pais (nombre) VALUES  ('Francia');
INSERT INTO pais (nombre) VALUES  ('Italia');